services:
  - type: web
    name: carbonscope-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: FRONTEND_URL
        value: "https://carbonscope.vercel.app"
    healthCheckPath: /health
    autoDeploy: true
